### ISSUE TITLE
Unable to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by chrisspen** [pykler/yajl-py#10]
If I install the yajl2 packages:

    sudo apt-get install libyajl2 libyajl-dev

and then try to install yajl-py from pypi:

    pip install yajl-py

I get a symbol error:

    Traceback (most recent call last):

      File "<string>", line 17, in <module>

      File "/usr/local/project_site/.env/build/yajl-py/setup.py", line 4, in <module>

        from yajl import __version__ as version

      File "yajl/__init__.py", line 13, in <module>

        from yajl_common import *

      File "yajl/yajl_common.py", line 87, in <module>

        yajl.yajl_gen_reset.restype = None

      File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__

        func = self.__getitem__(name)

      File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__

        func = self._FuncPtr((name_or_ordinal, self))

    AttributeError: /usr/lib/x86_64-linux-gnu/libyajl.so: undefined symbol: yajl_gen_reset

**Comment by chrisspen** [comment]
Essentially the similar to my last issue #8.

Per your previous advice, running `gcc -lyajl` shows yajl is installed correctly, and running `sudo ldconfig -p | grep yajl` shows:

    libyajl.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyajl.so.2

According to the [docs](http://packages.ubuntu.com/trusty/libyajl2), the 14.04 libyajl2 package is version 2.0.4-4. I tried running `pip install yajl-py==2.0.4-4` and `pip install yajl-py==2.0.4`, but it seems there's no exact match.

It looks like `pip install yajl-py==2.0.2` is a close enough match to 2.0.4 to install correclty, but this really seems hacky. This is the second time I haven't been able to install yajl-py out of the box. Is there any way to modify the installer to build/work for the available version, instead of the bleeding edge, which most distros are unlikely to have?

**Comment by pykler** [comment]
So in general yajl-py versions need to match the yajl version. I am
considering adding the yajl src to this codebase so that there is no need
to install a separate dependency which is distro specific etc.

Can you check what libyajl.so (not .so.2) is simlinked to?

**Comment by chrisspen** [comment]
/usr/lib/x86_64-linux-gnu/libyajl.so -> libyajl.so.1

**Comment by pykler** [comment]
So that looks like its pointing to yajl version 1. Do you know why you need
libyajl (vs libyajl2) on your system?

**Comment by chrisspen** [comment]
I don't. That's provided by the libyajl-dev package, which I thought I need for compiling yajl-py. I'm not sure that is version 1. The [docs](https://launchpad.net/ubuntu/trusty/+package/libyajl-dev) say it's version 2.

**Comment by pykler** [comment]
The current versions of yajl-py you just need the compiled so (no need for
libyajl-dev). If you do a `dpkg -S` on the so.1 file you will see that it
is a different package than the so.2 file that you pointed to in the
beginning of the thread.

Also the error you mentioned points to the fact that it is pointed to yajl
1.x and not 2. The reason it seems to work with a sightly older version of
yajl-py is that at version 2.0.2 of yajl-py the definitions to match the
headers file in yajl were not there ... This was added in 2.0.3 of yajl-py.
If you actually run the test suite you will notice that it doesn't quite
work.

**Comment by pykler** [comment]
Did this resolve your issues?

**Comment by pykler** [comment]
Hi Chris,

I just checked the [ubuntu package](http://packages.ubuntu.com/lucid/libyajl-dev) and you are right ... it is yajl2 based. The main issue you are having is the .so (with no .1 .2 suffix) is what yajl-py looks for. The .so suffix in your instance is not symlinked to the .so.2 which you had verified that it is yajl2 (it was symlinked to something else). If you fix that symlink or install yajl from source that should fix your issues.

As mentioned I will work on compiling yajl as part of yajl-py to avoid such issues moving forward.

**Comment by chrisspen** [comment]
Thanks. I haven't noticed any problems with it so far, but I haven't tested it too heavily yet. I'll try your suggestions if I run into any issues.
