### ISSUE TITLE
yajl-py fails to installl; ImportError

### ISSUE THREAD

**Issue by eddie-dunn** [pykler/yajl-py#15]
Trying to install from the after cloning from git:

    % pip install --user . 
    Processing /home/usrname/Upstream/yajl-py
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-x53ozjqa-build/setup.py", line 4, in <module>
            from yajl import __version__ as version
          File "/tmp/pip-x53ozjqa-build/yajl/__init__.py", line 13, in <module>
            from yajl_common import *
        ImportError: No module named 'yajl_common'

The same happens if I try to install it directly from PyPI.

**Comment by JeffLeFevre** [comment]
Same.  Using Python 3.4

**Comment by fabiant7t** [comment]
README.rst states that it requires "python 2.6 (or compatible)". So this is not an issue, but a feature request (that I would love to see as well :))

@pykler For allowing others to work on a Python 3 port, it would be great if pykler/MiniMockTest was Python3 compatible. I've seen a pull request over there that does just that based on the output of the 2to3 tool.

After 2to3ing my way through the yajl-py code and its tests, it seems to require someone with an understanding of ctypes and Python 3 types to fix this issue:

```
Traceback (most recent call last):
File "/home/fabian/yajl-py/tests/test_yajl_c.py", line 76, in test 
  parser.parse(f)
File "/home/fabian/yajl-py/tests/../yajl/yajl_parse.py", line 242, in parse
  stat = yajl.yajl_parse(hand, fileData, len(fileData))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by pykler** [comment]
There is a pull request #11 open that doesn't really work to make yajl-py python3 compatible. I am leaning towards accepting a PR that uses six such that yajl-py still works in python2.7; Will have a look at this shortly and ping back this issue.
