### ISSUE TITLE
ModuleNotFoundError: No module named 'yajl_common'

### ISSUE THREAD

**Issue by marceloslacerda** [pykler/yajl-py#19]
Using python 3.6 I'm getting an import error during the installation of yajl-py

    $ pip install yajl-py
    Collecting yajl-py
      Using cached yajl-py-2.1.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-to_jnimj/yajl-py/setup.py", line 4, in <module>
            from yajl import __version__ as version
          File "/tmp/pip-build-to_jnimj/yajl-py/yajl/__init__.py", line 13, in <module>
            from yajl_common import *
        ModuleNotFoundError: No module named 'yajl_common'
    
    $ python --version
    Python 3.6.2

    $ pip --version
    pip 9.0.1 from /home/msl09/.virtualenvs/telegram/lib/python3.6/site-packages (python 3.6)

I have tried installing yajl using the procedure in the "dep" target of the yajl-py Makefile.

**Comment by RaghuDevata** [comment]
I am also facing same issue.

 from yajl import __version__ as version
      File "C:\Users\devata\AppData\Local\Temp\pip-build-zjqgxowm\yajl-py\yajl\__init__.py", line 13, in <module>
        from yajl_common import *
    ModuleNotFoundError: No module named 'yajl_common'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\devata\AppData\Local\Temp\pip-build-zjqgxowm\yajl-py\

I am using 3.6 version (spyder - anaconda distribution )

**Comment by pykler** [comment]
Hi Raghu, looks like you are using older code. Saw that there was a mismatch on the version uploaded to pypi so bumped the version and re-uploaded. Please try now.
